language: node_js
sudo: required
cache:
  yarn: true
script: yarn run bootstrap && yarn run build && yarn run test && yarn run coverage
after_success:
  - cat ./packages/mobx-state-tree/coverage/lcov.info|./packages/mobx-state-tree/node_modules/coveralls/bin/coveralls.js
node_js:
  - "6.10.1"
